title: Quickstart Guides To Transmaxxing
description: Guides to help with transitioning
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

callouts:
  highlight:
    color: pink
    opacity: 0.3